package com.mycompany.controlvotaciones;
import java.util.List;
import javax.swing.JOptionPane;

public class RegistrarVoto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarVoto.class.getName());

 
  public RegistrarVoto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        // Cargar grados después de initComponents
        cargarGrados();
    }
    
    private void cargarGrados() {
        jComboBoxGrade.removeAllItems();
        jComboBoxGrade.addItem("Seleccionar Grado");

        List<Candidato> todos = BDXML.obtenerTodosCandidatos();

        for (Candidato c : todos) {
            boolean yaExiste = false;
            for (int i = 0; i < jComboBoxGrade.getItemCount(); i++) {
                if (jComboBoxGrade.getItemAt(i).equals(c.getGrade())) {
                    yaExiste = true;
                    break;
                }
            }
            if (!yaExiste) {
                jComboBoxGrade.addItem(c.getGrade());
            }
        }
    }

    private void cargarParticipantes(String gradoSeleccionado) {
        jComboBoxParticipante.removeAllItems();
        jComboBoxParticipante.addItem("Seleccionar Participante");

        if (gradoSeleccionado == null || gradoSeleccionado.equals("Seleccionar Grado")) {
            return;
        }

        List<Candidato> todos = BDXML.obtenerTodosCandidatos();

        for (Candidato c : todos) {
            if (c.getGrade().equals(gradoSeleccionado)) {
                jComboBoxParticipante.addItem(c.getFullName());
            }
        }
    }

  
  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxGrade = new javax.swing.JComboBox<>();
        jComboBoxParticipante = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextFieldVotos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("BACK");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Registrar Votos");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Grade:");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Participante:");

        jComboBoxGrade.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jComboBoxGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxGrade.addActionListener(this::jComboBoxGradeActionPerformed);

        jComboBoxParticipante.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jComboBoxParticipante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jToggleButton1.setText("SAVE");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);

        jTextFieldVotos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextFieldVotos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldVotosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVotos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel3)
                    .addContainerGap(346, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jTextFieldVotos))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(183, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Menu mp = new Menu();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGradeActionPerformed
if (jComboBoxGrade.getSelectedItem() == null) return;
        
        String grado = jComboBoxGrade.getSelectedItem().toString();
        cargarParticipantes(grado);
    }//GEN-LAST:event_jComboBoxGradeActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // PROTECCIÓN CONTRA NULL
        if (jComboBoxGrade.getSelectedItem() == null || jComboBoxParticipante.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar grado y participante.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String grado = jComboBoxGrade.getSelectedItem().toString();
        String participante = jComboBoxParticipante.getSelectedItem().toString();
        String votosStr = jTextFieldVotos.getText().trim();

        if (grado.equals("Seleccionar Grado") || participante.equals("Seleccionar Participante")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar grado y participante.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (votosStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la cantidad de votos.", "Error", JOptionPane.WARNING_MESSAGE);
            jTextFieldVotos.requestFocus();
            return;
        }

        try {
            int votos = Integer.parseInt(votosStr);
            if (votos <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad de votos debe ser mayor a 0.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (BDXML.registrarVotos(participante, votos)) {
                JOptionPane.showMessageDialog(this,
                    "¡" + votos + " voto(s) registrado(s) correctamente a:\n" + participante,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                jTextFieldVotos.setText("");
                // Recargar participantes del mismo grado
                cargarParticipantes(grado);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar los votos.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Solo se permiten números enteros.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextFieldVotosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldVotosKeyTyped
char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b') {
            evt.consume();
        }      // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVotosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new RegistrarVoto().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxGrade;
    private javax.swing.JComboBox<String> jComboBoxParticipante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldVotos;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
